import { format } from 'date-fns';
import { id } from 'date-fns/locale';
import { Employee, Search } from '../pages/model/employee.model';

export const employees: Employee[] = [
  {
    id: 1,
    username: 'Fadhil',
    firstName: 'Fadhil yusni',
    lastName: 'ramadhan',
    email: 'test@gmail.com',
    birthDate: new Date('1999-09-8'),
    basicSalary: 100000,
    status: 'Permanent',
    group: 'Digital Developer Program',
    description:
      'Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum',
  },
  {
    id: 2,
    username: 'Fadhil',
    firstName: 'Fadhil yusni',
    lastName: 'ramadhan',
    email: 'test@gmail.com',
    birthDate: new Date('1999-12-10'),
    basicSalary: 100000,
    status: 'Permanent',
    group: 'Digital Developer Program',
    description:
      'Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum',
  },
  {
    id: 3,
    username: 'CandacePerry',
    firstName: 'Mattie',
    lastName: 'Woodward',
    email: 'mattiewoodward@quilk.com',
    birthDate: new Date('2001-11-24'),
    basicSalary: 903611807,
    status: 'Contract',
    group: 'System Analyst',
    description:
      'Ea voluptate sit excepteur in cillum adipisicing in sunt dolore labore velit commodo. Esse ipsum eu proident dolor culpa sint fugiat sint voluptate veniam in incididunt adipisicing occaecat. Laborum proident velit est adipisicing sint magna. Enim tempor sit ad consectetur deserunt magna reprehenderit ex laborum nostrud dolor. Elit laborum quis do nisi cillum non ipsum.\r\n',
  },
  {
    id: 4,
    username: 'ConcepcionReese',
    firstName: 'Samantha',
    lastName: 'Dawson',
    email: 'samanthadawson@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 941916801,
    status: 'Contract',
    group: 'IT Support',
    description:
      'Consequat nulla amet elit deserunt ullamco minim qui sunt. Adipisicing deserunt velit reprehenderit dolor veniam in cupidatat quis. Non aliqua esse eu commodo nisi Lorem. Amet nulla non sit quis ad fugiat exercitation nostrud eu. Lorem exercitation dolor Lorem duis mollit ut.\r\n',
  },
  {
    id: 5,
    username: 'RamosHart',
    firstName: 'Kari',
    lastName: 'Valdez',
    email: 'karivaldez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 997416879,
    status: 'Permanent',
    group: 'IT Support',
    description:
      'Incididunt id ex officia eiusmod. Dolor officia duis non amet est officia est occaecat. Nulla sint qui occaecat esse dolore consequat esse labore excepteur.\r\n',
  },
  {
    id: 6,
    username: 'DavidsonKelly',
    firstName: 'Mclaughlin',
    lastName: 'Faulkner',
    email: 'mclaughlinfaulkner@quilk.com',
    birthDate: new Date('1992-05-09'),
    basicSalary: 912696595,
    status: 'Contract',
    group: 'Backend',
    description:
      'Enim ex duis adipisicing exercitation do. Nostrud non eu veniam ad ullamco voluptate aliqua ex commodo adipisicing occaecat ea tempor laborum. Dolor enim labore irure eiusmod Lorem enim dolor tempor cupidatat anim id exercitation ullamco. Veniam cillum ea dolor et officia deserunt anim sit nostrud. Sint adipisicing laboris est labore incididunt laboris aute sit.\r\n',
  },
  {
    id: 7,
    username: 'RichmondPreston',
    firstName: 'Brandy',
    lastName: 'Gates',
    email: 'brandygates@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 926674387,
    status: 'Permanent',
    group: 'Database',
    description:
      'Lorem laborum incididunt ad consectetur excepteur. Consectetur dolore deserunt id adipisicing consequat. Do mollit consequat proident est ex occaecat cupidatat enim sunt ad id. Id eiusmod qui dolor nostrud consectetur voluptate.\r\n',
  },
  {
    id: 8,
    username: 'GuyWynn',
    firstName: 'Robin',
    lastName: 'Bush',
    email: 'robinbush@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 909443146,
    status: 'Permanent',
    group: 'IT Support',
    description:
      'Aliquip id consectetur cillum eu et Lorem in ullamco amet elit cillum reprehenderit do id. Ipsum irure commodo eiusmod in est. Sint commodo sunt Lorem laboris dolor in occaecat. Duis cupidatat ad consectetur cillum ad duis nulla nostrud. Est do reprehenderit consequat proident.\r\n',
  },
  {
    id: 9,
    username: 'WeissTillman',
    firstName: 'Velazquez',
    lastName: 'Colon',
    email: 'velazquezcolon@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 844281498,
    status: 'Permanent',
    group: 'UI/UX',
    description:
      'Duis consectetur occaecat aliquip adipisicing amet ipsum ut et mollit ad elit excepteur. Aliquip excepteur elit fugiat duis mollit eiusmod dolor duis pariatur. Occaecat dolor veniam laborum ut adipisicing.\r\n',
  },
  {
    id: 10,
    username: 'SandovalGolden',
    firstName: 'Ebony',
    lastName: 'Dale',
    email: 'ebonydale@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 897117892,
    status: 'Contract',
    group: 'Frontend',
    description:
      'Minim exercitation nulla qui nisi. Ullamco esse qui laborum sint cupidatat exercitation incididunt consectetur enim et laboris eu. Ipsum minim eu exercitation ex. Et eiusmod anim ut dolor sit sit magna velit do fugiat elit nostrud laboris.\r\n',
  },
  {
    id: 11,
    username: 'BobbieMccoy',
    firstName: 'Whitfield',
    lastName: 'Juarez',
    email: 'whitfieldjuarez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 923297430,
    status: 'Contract',
    group: 'Digital Banking',
    description:
      'Quis eu dolor proident esse fugiat Lorem minim irure anim sint pariatur nostrud. Minim esse ea eu occaecat culpa. Aliqua adipisicing nulla laboris ea adipisicing incididunt ullamco ex. Adipisicing mollit deserunt deserunt laborum pariatur amet culpa fugiat sint consectetur adipisicing incididunt reprehenderit deserunt. Ullamco do eiusmod voluptate sint magna laborum. Nulla magna adipisicing nulla dolore cupidatat consectetur.\r\n',
  },
  {
    id: 12,
    username: 'StantonKnox',
    firstName: 'Petty',
    lastName: 'Lawrence',
    email: 'pettylawrence@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 943383779,
    status: 'Contract',
    group: 'Digital Banking',
    description:
      'Tempor in anim aliquip pariatur culpa dolore excepteur nisi cillum nostrud dolore nisi proident. Occaecat est aliquip adipisicing velit voluptate aliquip reprehenderit ullamco aliquip pariatur pariatur. Quis eu velit enim excepteur duis eiusmod tempor qui. Magna cillum et minim ipsum aliqua sunt commodo nulla mollit deserunt. Eiusmod culpa magna deserunt velit ad voluptate velit nostrud. Anim fugiat qui nulla reprehenderit tempor in qui consectetur labore tempor. Voluptate eu labore occaecat Lorem mollit.\r\n',
  },
  {
    id: 13,
    username: 'JeanetteSchmidt',
    firstName: 'Trudy',
    lastName: 'Duffy',
    email: 'trudyduffy@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 843203813,
    status: 'Contract',
    group: 'Database',
    description:
      'Mollit sit ipsum cillum dolore proident sit velit aute consectetur. Mollit tempor labore id Lorem ullamco consectetur veniam ipsum amet duis amet incididunt esse. Est aliqua do adipisicing fugiat ea anim tempor incididunt eu pariatur.\r\n',
  },
  {
    id: 14,
    username: 'WarrenMoon',
    firstName: 'Fry',
    lastName: 'Holmes',
    email: 'fryholmes@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 948126984,
    status: 'Contract',
    group: 'Backend',
    description:
      'In in irure ea ut commodo commodo. Dolor consectetur id anim deserunt anim. Nisi fugiat fugiat commodo cillum magna deserunt. Lorem commodo ex anim deserunt sunt.\r\n',
  },
  {
    id: 15,
    username: 'KnightFlowers',
    firstName: 'Lancaster',
    lastName: 'Cooper',
    email: 'lancastercooper@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 941664047,
    status: 'Permanent',
    group: 'Frontend',
    description:
      'Veniam laboris ex adipisicing quis anim ut velit sunt sint est ea. Enim ad proident esse incididunt est voluptate tempor velit labore do aliqua. Ex voluptate Lorem nostrud enim consequat quis aliqua commodo ullamco reprehenderit officia.\r\n',
  },
  {
    id: 16,
    username: 'DouglasBowman',
    firstName: 'Selena',
    lastName: 'Mcintyre',
    email: 'selenamcintyre@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 880224396,
    status: 'Permanent',
    group: 'UI/UX',
    description:
      'Nulla incididunt ullamco ex sint minim. Ex aliqua elit eiusmod minim incididunt qui eiusmod qui sunt veniam duis commodo ipsum. Cillum labore esse dolore ullamco commodo consectetur irure aliquip deserunt quis labore laboris consequat. Consectetur fugiat proident sunt occaecat excepteur cupidatat sunt Lorem dolore cupidatat enim id et. Sit aute proident consequat nisi deserunt ut dolore aute qui nisi magna ut voluptate. Proident non ut eiusmod amet adipisicing ullamco consectetur laboris ullamco consequat. Veniam enim ut et non consectetur laborum voluptate aliqua.\r\n',
  },
  {
    id: 17,
    username: 'MooneyMckay',
    firstName: 'Camille',
    lastName: 'Moreno',
    email: 'camillemoreno@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 884444261,
    status: 'Contract',
    group: 'Frontend',
    description:
      'Nisi laborum voluptate culpa aliqua do reprehenderit in consequat. Quis qui consequat laborum veniam aliquip nostrud esse aliqua consectetur esse ad. Dolor ut non laborum consequat nisi dolore enim culpa in. Ullamco proident aliqua nisi ullamco. Cupidatat id excepteur ipsum laboris dolor nisi officia voluptate occaecat voluptate officia. Nostrud ut mollit est ea velit deserunt veniam officia reprehenderit ad. Minim exercitation adipisicing veniam officia eiusmod.\r\n',
  },
  {
    id: 18,
    username: 'FrancisBurton',
    firstName: 'Jane',
    lastName: 'Rodriquez',
    email: 'janerodriquez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 815385667,
    status: 'Permanent',
    group: 'Frontend',
    description:
      'Exercitation dolore velit reprehenderit elit magna laboris reprehenderit. Lorem commodo ea eu tempor labore quis minim. Enim mollit sit amet fugiat dolor qui. Eu dolor eu nostrud adipisicing sit duis. Culpa reprehenderit voluptate eiusmod exercitation et mollit consequat sit non sit exercitation eiusmod amet.\r\n',
  },
  {
    id: 19,
    username: 'CantrellRiley',
    firstName: 'Darcy',
    lastName: 'Hampton',
    email: 'darcyhampton@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 818309335,
    status: 'Permanent',
    group: 'Security',
    description:
      'Fugiat deserunt reprehenderit laboris cillum ea. Duis ea irure mollit non nulla mollit dolor anim officia. Anim reprehenderit fugiat id tempor ex fugiat incididunt enim adipisicing mollit incididunt do.\r\n',
  },
  {
    id: 20,
    username: 'TranRios',
    firstName: 'Felicia',
    lastName: 'Ray',
    email: 'feliciaray@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 841900417,
    status: 'Permanent',
    group: 'Digital developer',
    description:
      'Incididunt anim officia excepteur incididunt anim. Nostrud dolor culpa elit ipsum exercitation aliquip. Adipisicing fugiat ipsum eu qui excepteur sit enim veniam id labore nisi proident quis. Qui cupidatat adipisicing amet tempor est deserunt incididunt tempor proident cillum duis do excepteur eiusmod.\r\n',
  },
  {
    id: 21,
    username: 'DebraGuerra',
    firstName: 'Angela',
    lastName: 'Glenn',
    email: 'angelaglenn@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 840160597,
    status: 'Permanent',
    group: 'Digital developer',
    description:
      'Reprehenderit eiusmod reprehenderit ipsum exercitation. Minim est nisi Lorem ipsum proident qui labore anim deserunt do veniam culpa cupidatat. Ut fugiat quis labore voluptate consequat nulla ullamco eu dolor culpa consectetur deserunt id labore. Laborum deserunt esse eiusmod veniam sint eiusmod dolore consequat magna. Minim cupidatat commodo eiusmod velit reprehenderit.\r\n',
  },
  {
    id: 22,
    username: 'CarmenPeck',
    firstName: 'Finley',
    lastName: 'Vincent',
    email: 'finleyvincent@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 890204791,
    status: 'Permanent',
    group: 'Backend',
    description:
      'Reprehenderit cillum ut sit veniam laborum anim nisi sit nulla. Culpa ex nisi ex sit elit minim officia tempor id id fugiat sint. Ad ullamco mollit esse enim adipisicing labore voluptate officia aliqua fugiat dolore.\r\n',
  },
  {
    id: 23,
    username: 'HallieBradford',
    firstName: 'Lamb',
    lastName: 'Solomon',
    email: 'lambsolomon@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 959351582,
    status: 'Contract',
    group: 'Security',
    description:
      'Sunt ut exercitation reprehenderit veniam dolore quis minim deserunt elit magna quis in. Consectetur eu reprehenderit pariatur irure elit. Culpa ipsum dolore proident velit non tempor nisi dolore. Amet enim do exercitation nulla anim. Occaecat laborum eu id nostrud excepteur anim exercitation est deserunt sunt culpa consectetur exercitation. Anim in commodo irure do nisi ex non sint ad reprehenderit sit esse ea deserunt. Ullamco velit est anim aliquip occaecat.\r\n',
  },
  {
    id: 24,
    username: 'BenderPaul',
    firstName: 'Pearl',
    lastName: 'Dickson',
    email: 'pearldickson@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 897007864,
    status: 'Permanent',
    group: 'System Analyst',
    description:
      'Deserunt irure nisi occaecat amet officia exercitation nulla id voluptate elit nisi deserunt est elit. Ullamco cupidatat aliqua veniam exercitation duis laborum do esse proident qui in in non. Excepteur amet incididunt exercitation deserunt mollit. Adipisicing dolor anim cupidatat cupidatat occaecat commodo occaecat.\r\n',
  },
  {
    id: 25,
    username: 'GarzaNorton',
    firstName: 'Drake',
    lastName: 'Burch',
    email: 'drakeburch@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 902269207,
    status: 'Contract',
    group: 'UI/UX',
    description:
      'Quis proident do amet dolore magna ut eiusmod. Nulla veniam eu sint cupidatat. Consectetur duis nostrud labore incididunt ullamco consectetur laboris commodo in ut labore. Commodo commodo commodo eiusmod qui excepteur adipisicing eiusmod excepteur pariatur ullamco consequat. Do do deserunt id magna id pariatur voluptate nulla irure nulla sit laborum adipisicing. Enim consequat tempor non duis eu anim nisi dolore aute laboris irure reprehenderit sit minim. Sit pariatur ea aliquip Lorem.\r\n',
  },
  {
    id: 26,
    username: 'MinniePark',
    firstName: 'Owens',
    lastName: 'Stein',
    email: 'owensstein@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 944676533,
    status: 'Permanent',
    group: 'Backend',
    description:
      'Fugiat non sit voluptate officia. Lorem voluptate occaecat sunt quis proident deserunt. Esse Lorem voluptate incididunt mollit anim esse sit. Adipisicing duis ipsum non veniam qui quis labore aliquip ea. Duis consequat pariatur reprehenderit occaecat voluptate enim dolor adipisicing dolore Lorem et.\r\n',
  },
  {
    id: 27,
    username: 'HubbardMedina',
    firstName: 'Bridget',
    lastName: 'Pitts',
    email: 'bridgetpitts@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 922853081,
    status: 'Contract',
    group: 'UI/UX',
    description:
      'Consequat dolor exercitation aute quis laboris qui cupidatat veniam culpa incididunt. Pariatur incididunt velit est velit laborum ea consequat. Duis culpa id et ea elit consequat laborum aliquip quis irure labore reprehenderit exercitation. Eu ullamco cillum sit laborum dolor dolor irure aliquip esse magna. Anim reprehenderit sint tempor elit consequat tempor duis sit.\r\n',
  },
  {
    id: 28,
    username: 'MarcyBuckley',
    firstName: 'Chris',
    lastName: 'Cortez',
    email: 'chriscortez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 858592628,
    status: 'Contract',
    group: 'Security',
    description:
      'Labore do eu minim cillum exercitation aliqua in. Laboris esse occaecat amet magna Lorem dolor dolor non. Elit velit esse incididunt cillum irure in. Tempor aliqua qui Lorem adipisicing laborum sit deserunt magna commodo quis incididunt cillum aliqua. Deserunt sit non sit adipisicing eiusmod enim quis reprehenderit. Eu duis consectetur irure reprehenderit non enim Lorem.\r\n',
  },
  {
    id: 29,
    username: 'MadgeKerr',
    firstName: 'Savannah',
    lastName: 'Guzman',
    email: 'savannahguzman@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 840096184,
    status: 'Permanent',
    group: 'Database',
    description:
      'Reprehenderit amet commodo ullamco aute minim Lorem ex sit veniam ut in in commodo. Quis deserunt ex ullamco ex commodo eiusmod aliquip. Consequat ut sunt eu ut in esse voluptate magna. Pariatur Lorem est nisi ad laboris aliqua adipisicing. Anim esse occaecat sint cupidatat exercitation proident occaecat sunt incididunt veniam sint laboris. Tempor velit laborum enim ut cupidatat irure cupidatat dolor ullamco cupidatat enim proident.\r\n',
  },
  {
    id: 30,
    username: 'LeighCantu',
    firstName: 'Farley',
    lastName: 'Wallace',
    email: 'farleywallace@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 985704294,
    status: 'Contract',
    group: 'UI/UX',
    description:
      'Laborum laborum sunt qui ad proident laborum nisi. Reprehenderit esse magna aliquip amet exercitation proident. Labore ut consequat enim magna nisi est adipisicing officia ipsum et pariatur. Laboris aute officia officia non id do officia ea.\r\n',
  },
  {
    id: 31,
    username: 'ThorntonCurry',
    firstName: 'Patrica',
    lastName: 'Hebert',
    email: 'patricahebert@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 830845098,
    status: 'Permanent',
    group: 'IT Support',
    description:
      'Qui aliquip est occaecat cupidatat voluptate quis commodo irure nisi pariatur. Labore ex magna tempor sint. Non officia aliquip sunt ea et est quis laborum enim exercitation minim. Lorem sit reprehenderit cupidatat tempor aute. Consectetur Lorem id reprehenderit esse laboris qui proident exercitation amet labore sit pariatur sint incididunt. Ullamco laborum enim elit excepteur adipisicing mollit nisi irure veniam laborum minim duis. Enim fugiat magna cupidatat occaecat tempor dolore nostrud Lorem eu nostrud officia ad anim adipisicing.\r\n',
  },
  {
    id: 32,
    username: 'DotsonJoseph',
    firstName: 'Kimberly',
    lastName: 'Short',
    email: 'kimberlyshort@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 947629888,
    status: 'Contract',
    group: 'IT Support',
    description:
      'Aute anim anim laboris consequat excepteur. Anim ea magna Lorem cupidatat laborum irure pariatur amet occaecat enim. Dolor incididunt laboris pariatur id ullamco quis non consectetur quis adipisicing deserunt. Tempor dolor occaecat eiusmod magna consectetur quis cupidatat labore. Veniam fugiat Lorem mollit veniam magna ut laboris. Cillum voluptate fugiat esse deserunt.\r\n',
  },
  {
    id: 33,
    username: 'BrigitteKinney',
    firstName: 'Claudine',
    lastName: 'Webb',
    email: 'claudinewebb@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 931911211,
    status: 'Permanent',
    group: 'Mobile',
    description:
      'Nostrud excepteur ex velit duis nulla esse officia culpa deserunt Lorem. Enim magna ipsum magna do Lorem officia excepteur cupidatat. Magna dolore quis culpa Lorem eiusmod fugiat culpa consectetur officia. Mollit irure incididunt occaecat exercitation. Laboris nulla adipisicing commodo proident ipsum enim amet magna do laboris elit.\r\n',
  },
  {
    id: 34,
    username: 'BarnettYang',
    firstName: 'Darla',
    lastName: 'Arnold',
    email: 'darlaarnold@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 816686837,
    status: 'Contract',
    group: 'Digital developer',
    description:
      'Non enim nostrud laboris nisi eiusmod amet magna sit veniam ad. Irure deserunt qui exercitation culpa nostrud nisi non. Elit minim sit non id id ullamco ullamco mollit adipisicing duis irure reprehenderit cupidatat. Aliqua minim tempor cupidatat id.\r\n',
  },
  {
    id: 35,
    username: 'BlankenshipBoone',
    firstName: 'Silva',
    lastName: 'Jarvis',
    email: 'silvajarvis@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 902851631,
    status: 'Contract',
    group: 'Mobile',
    description:
      'Amet qui dolore ea pariatur fugiat veniam eiusmod. Magna fugiat labore elit nostrud quis velit enim Lorem elit. Reprehenderit sunt esse velit id. Eiusmod duis nostrud et ullamco dolor excepteur tempor incididunt adipisicing.\r\n',
  },
  {
    id: 36,
    username: 'GraceMcclure',
    firstName: 'Norton',
    lastName: 'Small',
    email: 'nortonsmall@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 815185817,
    status: 'Contract',
    group: 'Frontend',
    description:
      'Irure proident esse cupidatat et quis nostrud reprehenderit in do Lorem ex ad. Mollit cupidatat adipisicing dolore non labore elit est nisi et cillum laboris culpa. Cupidatat mollit exercitation adipisicing pariatur ea anim in mollit est aliqua dolore ullamco commodo. Ut amet cillum id nostrud aliquip adipisicing nulla ut ullamco consectetur eu mollit. Do tempor ad adipisicing elit enim duis consequat laboris non laboris ad excepteur. Proident exercitation aute esse reprehenderit mollit consectetur excepteur in culpa et mollit adipisicing aliqua.\r\n',
  },
  {
    id: 37,
    username: 'VickieRandolph',
    firstName: 'Hodge',
    lastName: 'Strong',
    email: 'hodgestrong@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 820423851,
    status: 'Permanent',
    group: 'Digital developer',
    description:
      'Officia qui velit ut cillum cillum non qui nostrud exercitation ipsum. Irure consectetur ut cupidatat ut. Magna eu cupidatat est cupidatat commodo exercitation sint minim duis ipsum ea qui. Fugiat adipisicing fugiat velit ut ut do nostrud ea elit in minim tempor. Ipsum commodo ex enim Lorem esse labore laboris veniam in adipisicing irure est commodo. Minim aliqua cillum consectetur cupidatat Lorem consequat. Qui eiusmod veniam nostrud sint.\r\n',
  },
  {
    id: 38,
    username: 'BoyleDonaldson',
    firstName: 'Bryan',
    lastName: 'Alexander',
    email: 'bryanalexander@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 951337016,
    status: 'Permanent',
    group: 'IT Support',
    description:
      'Velit proident ea in ipsum et adipisicing laboris. Et adipisicing reprehenderit in deserunt ex dolor aliquip minim Lorem consequat est quis magna. Tempor dolor mollit minim est enim veniam tempor velit culpa veniam. Commodo ut ut velit cillum ad qui dolore. Labore minim proident sunt culpa adipisicing ad non enim eiusmod. Dolore enim irure Lorem id id qui eu excepteur elit qui irure. Id velit elit qui nisi ullamco consequat.\r\n',
  },
  {
    id: 39,
    username: 'StephanieCalderon',
    firstName: 'Wade',
    lastName: 'Ayala',
    email: 'wadeayala@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 919475223,
    status: 'Contract',
    group: 'System Analyst',
    description:
      'Ullamco sunt elit cupidatat do est sit et culpa nostrud et. Magna occaecat incididunt do enim occaecat deserunt ex nostrud voluptate. Culpa ullamco occaecat amet pariatur reprehenderit nisi consequat occaecat nostrud eu dolore. Labore ea mollit dolor tempor duis sit nostrud do fugiat veniam deserunt et ex. Reprehenderit tempor ullamco anim laborum ea elit. Culpa Lorem mollit incididunt commodo eiusmod pariatur fugiat ullamco amet.\r\n',
  },
  {
    id: 40,
    username: 'WallsYates',
    firstName: 'David',
    lastName: 'Vang',
    email: 'davidvang@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 968345544,
    status: 'Permanent',
    group: 'Digital Banking',
    description:
      'Id sint laborum cupidatat ipsum sint do nulla proident quis et ipsum irure. Laborum anim ex eiusmod dolore. Eu Lorem consequat et excepteur anim ea incididunt proident esse quis enim consequat commodo non. Proident do elit adipisicing esse sunt mollit tempor pariatur consectetur. Et amet ipsum mollit reprehenderit. Lorem anim ea aliqua enim laborum et esse amet enim commodo mollit anim veniam. Labore officia commodo qui elit et id duis sunt.\r\n',
  },
  {
    id: 41,
    username: 'KirbyDuran',
    firstName: 'Cristina',
    lastName: 'Lester',
    email: 'cristinalester@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 846572485,
    status: 'Permanent',
    group: 'System Analyst',
    description:
      'Ad aute nulla quis irure consectetur cillum sint cupidatat mollit veniam proident veniam qui eiusmod. Cupidatat sint deserunt mollit labore. Adipisicing tempor dolore proident nisi fugiat ullamco duis in culpa fugiat anim incididunt aute occaecat.\r\n',
  },
  {
    id: 42,
    username: 'Fadhil',
    firstName: 'Fadhil yusni',
    lastName: 'ramadhan',
    email: 'test@gmail.com',
    birthDate: new Date('1999-09-8'),
    basicSalary: 100000,
    status: 'Permanent',
    group: 'Digital Developer Program',
    description:
      'Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum',
  },
  {
    id: 43,
    username: 'Fadhil',
    firstName: 'Fadhil yusni',
    lastName: 'ramadhan',
    email: 'test@gmail.com',
    birthDate: new Date('1999-12-10'),
    basicSalary: 100000,
    status: 'Permanent',
    group: 'Digital Developer Program',
    description:
      'Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum',
  },
  {
    id: 44,
    username: 'CandacePerry',
    firstName: 'Mattie',
    lastName: 'Woodward',
    email: 'mattiewoodward@quilk.com',
    birthDate: new Date('2001-11-24'),
    basicSalary: 903611807,
    status: 'Contract',
    group: 'System Analyst',
    description:
      'Ea voluptate sit excepteur in cillum adipisicing in sunt dolore labore velit commodo. Esse ipsum eu proident dolor culpa sint fugiat sint voluptate veniam in incididunt adipisicing occaecat. Laborum proident velit est adipisicing sint magna. Enim tempor sit ad consectetur deserunt magna reprehenderit ex laborum nostrud dolor. Elit laborum quis do nisi cillum non ipsum.\r\n',
  },
  {
    id: 45,
    username: 'ConcepcionReese',
    firstName: 'Samantha',
    lastName: 'Dawson',
    email: 'samanthadawson@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 941916801,
    status: 'Contract',
    group: 'IT Support',
    description:
      'Consequat nulla amet elit deserunt ullamco minim qui sunt. Adipisicing deserunt velit reprehenderit dolor veniam in cupidatat quis. Non aliqua esse eu commodo nisi Lorem. Amet nulla non sit quis ad fugiat exercitation nostrud eu. Lorem exercitation dolor Lorem duis mollit ut.\r\n',
  },
  {
    id: 46,
    username: 'RamosHart',
    firstName: 'Kari',
    lastName: 'Valdez',
    email: 'karivaldez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 997416879,
    status: 'Permanent',
    group: 'IT Support',
    description:
      'Incididunt id ex officia eiusmod. Dolor officia duis non amet est officia est occaecat. Nulla sint qui occaecat esse dolore consequat esse labore excepteur.\r\n',
  },
  {
    id: 47,
    username: 'DavidsonKelly',
    firstName: 'Mclaughlin',
    lastName: 'Faulkner',
    email: 'mclaughlinfaulkner@quilk.com',
    birthDate: new Date('1992-05-09'),
    basicSalary: 912696595,
    status: 'Contract',
    group: 'Backend',
    description:
      'Enim ex duis adipisicing exercitation do. Nostrud non eu veniam ad ullamco voluptate aliqua ex commodo adipisicing occaecat ea tempor laborum. Dolor enim labore irure eiusmod Lorem enim dolor tempor cupidatat anim id exercitation ullamco. Veniam cillum ea dolor et officia deserunt anim sit nostrud. Sint adipisicing laboris est labore incididunt laboris aute sit.\r\n',
  },
  {
    id: 48,
    username: 'RichmondPreston',
    firstName: 'Brandy',
    lastName: 'Gates',
    email: 'brandygates@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 926674387,
    status: 'Permanent',
    group: 'Database',
    description:
      'Lorem laborum incididunt ad consectetur excepteur. Consectetur dolore deserunt id adipisicing consequat. Do mollit consequat proident est ex occaecat cupidatat enim sunt ad id. Id eiusmod qui dolor nostrud consectetur voluptate.\r\n',
  },
  {
    id: 49,
    username: 'GuyWynn',
    firstName: 'Robin',
    lastName: 'Bush',
    email: 'robinbush@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 909443146,
    status: 'Permanent',
    group: 'IT Support',
    description:
      'Aliquip id consectetur cillum eu et Lorem in ullamco amet elit cillum reprehenderit do id. Ipsum irure commodo eiusmod in est. Sint commodo sunt Lorem laboris dolor in occaecat. Duis cupidatat ad consectetur cillum ad duis nulla nostrud. Est do reprehenderit consequat proident.\r\n',
  },
  {
    id: 50,
    username: 'WeissTillman',
    firstName: 'Velazquez',
    lastName: 'Colon',
    email: 'velazquezcolon@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 844281498,
    status: 'Permanent',
    group: 'UI/UX',
    description:
      'Duis consectetur occaecat aliquip adipisicing amet ipsum ut et mollit ad elit excepteur. Aliquip excepteur elit fugiat duis mollit eiusmod dolor duis pariatur. Occaecat dolor veniam laborum ut adipisicing.\r\n',
  },
  {
    id: 51,
    username: 'SandovalGolden',
    firstName: 'Ebony',
    lastName: 'Dale',
    email: 'ebonydale@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 897117892,
    status: 'Contract',
    group: 'Frontend',
    description:
      'Minim exercitation nulla qui nisi. Ullamco esse qui laborum sint cupidatat exercitation incididunt consectetur enim et laboris eu. Ipsum minim eu exercitation ex. Et eiusmod anim ut dolor sit sit magna velit do fugiat elit nostrud laboris.\r\n',
  },
  {
    id: 52,
    username: 'BobbieMccoy',
    firstName: 'Whitfield',
    lastName: 'Juarez',
    email: 'whitfieldjuarez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 923297430,
    status: 'Contract',
    group: 'Digital Banking',
    description:
      'Quis eu dolor proident esse fugiat Lorem minim irure anim sint pariatur nostrud. Minim esse ea eu occaecat culpa. Aliqua adipisicing nulla laboris ea adipisicing incididunt ullamco ex. Adipisicing mollit deserunt deserunt laborum pariatur amet culpa fugiat sint consectetur adipisicing incididunt reprehenderit deserunt. Ullamco do eiusmod voluptate sint magna laborum. Nulla magna adipisicing nulla dolore cupidatat consectetur.\r\n',
  },
  {
    id: 53,
    username: 'StantonKnox',
    firstName: 'Petty',
    lastName: 'Lawrence',
    email: 'pettylawrence@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 943383779,
    status: 'Contract',
    group: 'Digital Banking',
    description:
      'Tempor in anim aliquip pariatur culpa dolore excepteur nisi cillum nostrud dolore nisi proident. Occaecat est aliquip adipisicing velit voluptate aliquip reprehenderit ullamco aliquip pariatur pariatur. Quis eu velit enim excepteur duis eiusmod tempor qui. Magna cillum et minim ipsum aliqua sunt commodo nulla mollit deserunt. Eiusmod culpa magna deserunt velit ad voluptate velit nostrud. Anim fugiat qui nulla reprehenderit tempor in qui consectetur labore tempor. Voluptate eu labore occaecat Lorem mollit.\r\n',
  },
  {
    id: 54,
    username: 'JeanetteSchmidt',
    firstName: 'Trudy',
    lastName: 'Duffy',
    email: 'trudyduffy@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 843203813,
    status: 'Contract',
    group: 'Database',
    description:
      'Mollit sit ipsum cillum dolore proident sit velit aute consectetur. Mollit tempor labore id Lorem ullamco consectetur veniam ipsum amet duis amet incididunt esse. Est aliqua do adipisicing fugiat ea anim tempor incididunt eu pariatur.\r\n',
  },
  {
    id: 55,
    username: 'WarrenMoon',
    firstName: 'Fry',
    lastName: 'Holmes',
    email: 'fryholmes@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 948126984,
    status: 'Contract',
    group: 'Backend',
    description:
      'In in irure ea ut commodo commodo. Dolor consectetur id anim deserunt anim. Nisi fugiat fugiat commodo cillum magna deserunt. Lorem commodo ex anim deserunt sunt.\r\n',
  },
  {
    id: 56,
    username: 'KnightFlowers',
    firstName: 'Lancaster',
    lastName: 'Cooper',
    email: 'lancastercooper@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 941664047,
    status: 'Permanent',
    group: 'Frontend',
    description:
      'Veniam laboris ex adipisicing quis anim ut velit sunt sint est ea. Enim ad proident esse incididunt est voluptate tempor velit labore do aliqua. Ex voluptate Lorem nostrud enim consequat quis aliqua commodo ullamco reprehenderit officia.\r\n',
  },
  {
    id: 57,
    username: 'DouglasBowman',
    firstName: 'Selena',
    lastName: 'Mcintyre',
    email: 'selenamcintyre@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 880224396,
    status: 'Permanent',
    group: 'UI/UX',
    description:
      'Nulla incididunt ullamco ex sint minim. Ex aliqua elit eiusmod minim incididunt qui eiusmod qui sunt veniam duis commodo ipsum. Cillum labore esse dolore ullamco commodo consectetur irure aliquip deserunt quis labore laboris consequat. Consectetur fugiat proident sunt occaecat excepteur cupidatat sunt Lorem dolore cupidatat enim id et. Sit aute proident consequat nisi deserunt ut dolore aute qui nisi magna ut voluptate. Proident non ut eiusmod amet adipisicing ullamco consectetur laboris ullamco consequat. Veniam enim ut et non consectetur laborum voluptate aliqua.\r\n',
  },
  {
    id: 58,
    username: 'MooneyMckay',
    firstName: 'Camille',
    lastName: 'Moreno',
    email: 'camillemoreno@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 884444261,
    status: 'Contract',
    group: 'Frontend',
    description:
      'Nisi laborum voluptate culpa aliqua do reprehenderit in consequat. Quis qui consequat laborum veniam aliquip nostrud esse aliqua consectetur esse ad. Dolor ut non laborum consequat nisi dolore enim culpa in. Ullamco proident aliqua nisi ullamco. Cupidatat id excepteur ipsum laboris dolor nisi officia voluptate occaecat voluptate officia. Nostrud ut mollit est ea velit deserunt veniam officia reprehenderit ad. Minim exercitation adipisicing veniam officia eiusmod.\r\n',
  },
  {
    id: 59,
    username: 'FrancisBurton',
    firstName: 'Jane',
    lastName: 'Rodriquez',
    email: 'janerodriquez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 815385667,
    status: 'Permanent',
    group: 'Frontend',
    description:
      'Exercitation dolore velit reprehenderit elit magna laboris reprehenderit. Lorem commodo ea eu tempor labore quis minim. Enim mollit sit amet fugiat dolor qui. Eu dolor eu nostrud adipisicing sit duis. Culpa reprehenderit voluptate eiusmod exercitation et mollit consequat sit non sit exercitation eiusmod amet.\r\n',
  },
  {
    id: 60,
    username: 'CantrellRiley',
    firstName: 'Darcy',
    lastName: 'Hampton',
    email: 'darcyhampton@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 818309335,
    status: 'Permanent',
    group: 'Security',
    description:
      'Fugiat deserunt reprehenderit laboris cillum ea. Duis ea irure mollit non nulla mollit dolor anim officia. Anim reprehenderit fugiat id tempor ex fugiat incididunt enim adipisicing mollit incididunt do.\r\n',
  },
  {
    id: 61,
    username: 'TranRios',
    firstName: 'Felicia',
    lastName: 'Ray',
    email: 'feliciaray@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 841900417,
    status: 'Permanent',
    group: 'Digital developer',
    description:
      'Incididunt anim officia excepteur incididunt anim. Nostrud dolor culpa elit ipsum exercitation aliquip. Adipisicing fugiat ipsum eu qui excepteur sit enim veniam id labore nisi proident quis. Qui cupidatat adipisicing amet tempor est deserunt incididunt tempor proident cillum duis do excepteur eiusmod.\r\n',
  },
  {
    id: 62,
    username: 'DebraGuerra',
    firstName: 'Angela',
    lastName: 'Glenn',
    email: 'angelaglenn@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 840160597,
    status: 'Permanent',
    group: 'Digital developer',
    description:
      'Reprehenderit eiusmod reprehenderit ipsum exercitation. Minim est nisi Lorem ipsum proident qui labore anim deserunt do veniam culpa cupidatat. Ut fugiat quis labore voluptate consequat nulla ullamco eu dolor culpa consectetur deserunt id labore. Laborum deserunt esse eiusmod veniam sint eiusmod dolore consequat magna. Minim cupidatat commodo eiusmod velit reprehenderit.\r\n',
  },
  {
    id: 63,
    username: 'CarmenPeck',
    firstName: 'Finley',
    lastName: 'Vincent',
    email: 'finleyvincent@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 890204791,
    status: 'Permanent',
    group: 'Backend',
    description:
      'Reprehenderit cillum ut sit veniam laborum anim nisi sit nulla. Culpa ex nisi ex sit elit minim officia tempor id id fugiat sint. Ad ullamco mollit esse enim adipisicing labore voluptate officia aliqua fugiat dolore.\r\n',
  },
  {
    id: 64,
    username: 'HallieBradford',
    firstName: 'Lamb',
    lastName: 'Solomon',
    email: 'lambsolomon@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 959351582,
    status: 'Contract',
    group: 'Security',
    description:
      'Sunt ut exercitation reprehenderit veniam dolore quis minim deserunt elit magna quis in. Consectetur eu reprehenderit pariatur irure elit. Culpa ipsum dolore proident velit non tempor nisi dolore. Amet enim do exercitation nulla anim. Occaecat laborum eu id nostrud excepteur anim exercitation est deserunt sunt culpa consectetur exercitation. Anim in commodo irure do nisi ex non sint ad reprehenderit sit esse ea deserunt. Ullamco velit est anim aliquip occaecat.\r\n',
  },
  {
    id: 65,
    username: 'BenderPaul',
    firstName: 'Pearl',
    lastName: 'Dickson',
    email: 'pearldickson@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 897007864,
    status: 'Permanent',
    group: 'System Analyst',
    description:
      'Deserunt irure nisi occaecat amet officia exercitation nulla id voluptate elit nisi deserunt est elit. Ullamco cupidatat aliqua veniam exercitation duis laborum do esse proident qui in in non. Excepteur amet incididunt exercitation deserunt mollit. Adipisicing dolor anim cupidatat cupidatat occaecat commodo occaecat.\r\n',
  },
  {
    id: 66,
    username: 'GarzaNorton',
    firstName: 'Drake',
    lastName: 'Burch',
    email: 'drakeburch@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 902269207,
    status: 'Contract',
    group: 'UI/UX',
    description:
      'Quis proident do amet dolore magna ut eiusmod. Nulla veniam eu sint cupidatat. Consectetur duis nostrud labore incididunt ullamco consectetur laboris commodo in ut labore. Commodo commodo commodo eiusmod qui excepteur adipisicing eiusmod excepteur pariatur ullamco consequat. Do do deserunt id magna id pariatur voluptate nulla irure nulla sit laborum adipisicing. Enim consequat tempor non duis eu anim nisi dolore aute laboris irure reprehenderit sit minim. Sit pariatur ea aliquip Lorem.\r\n',
  },
  {
    id: 67,
    username: 'MinniePark',
    firstName: 'Owens',
    lastName: 'Stein',
    email: 'owensstein@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 944676533,
    status: 'Permanent',
    group: 'Backend',
    description:
      'Fugiat non sit voluptate officia. Lorem voluptate occaecat sunt quis proident deserunt. Esse Lorem voluptate incididunt mollit anim esse sit. Adipisicing duis ipsum non veniam qui quis labore aliquip ea. Duis consequat pariatur reprehenderit occaecat voluptate enim dolor adipisicing dolore Lorem et.\r\n',
  },
  {
    id: 68,
    username: 'HubbardMedina',
    firstName: 'Bridget',
    lastName: 'Pitts',
    email: 'bridgetpitts@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 922853081,
    status: 'Contract',
    group: 'UI/UX',
    description:
      'Consequat dolor exercitation aute quis laboris qui cupidatat veniam culpa incididunt. Pariatur incididunt velit est velit laborum ea consequat. Duis culpa id et ea elit consequat laborum aliquip quis irure labore reprehenderit exercitation. Eu ullamco cillum sit laborum dolor dolor irure aliquip esse magna. Anim reprehenderit sint tempor elit consequat tempor duis sit.\r\n',
  },
  {
    id: 69,
    username: 'MarcyBuckley',
    firstName: 'Chris',
    lastName: 'Cortez',
    email: 'chriscortez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 858592628,
    status: 'Contract',
    group: 'Security',
    description:
      'Labore do eu minim cillum exercitation aliqua in. Laboris esse occaecat amet magna Lorem dolor dolor non. Elit velit esse incididunt cillum irure in. Tempor aliqua qui Lorem adipisicing laborum sit deserunt magna commodo quis incididunt cillum aliqua. Deserunt sit non sit adipisicing eiusmod enim quis reprehenderit. Eu duis consectetur irure reprehenderit non enim Lorem.\r\n',
  },
  {
    id: 70,
    username: 'MadgeKerr',
    firstName: 'Savannah',
    lastName: 'Guzman',
    email: 'savannahguzman@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 840096184,
    status: 'Permanent',
    group: 'Database',
    description:
      'Reprehenderit amet commodo ullamco aute minim Lorem ex sit veniam ut in in commodo. Quis deserunt ex ullamco ex commodo eiusmod aliquip. Consequat ut sunt eu ut in esse voluptate magna. Pariatur Lorem est nisi ad laboris aliqua adipisicing. Anim esse occaecat sint cupidatat exercitation proident occaecat sunt incididunt veniam sint laboris. Tempor velit laborum enim ut cupidatat irure cupidatat dolor ullamco cupidatat enim proident.\r\n',
  },
  {
    id: 71,
    username: 'LeighCantu',
    firstName: 'Farley',
    lastName: 'Wallace',
    email: 'farleywallace@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 985704294,
    status: 'Contract',
    group: 'UI/UX',
    description:
      'Laborum laborum sunt qui ad proident laborum nisi. Reprehenderit esse magna aliquip amet exercitation proident. Labore ut consequat enim magna nisi est adipisicing officia ipsum et pariatur. Laboris aute officia officia non id do officia ea.\r\n',
  },
  {
    id: 72,
    username: 'ThorntonCurry',
    firstName: 'Patrica',
    lastName: 'Hebert',
    email: 'patricahebert@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 830845098,
    status: 'Permanent',
    group: 'IT Support',
    description:
      'Qui aliquip est occaecat cupidatat voluptate quis commodo irure nisi pariatur. Labore ex magna tempor sint. Non officia aliquip sunt ea et est quis laborum enim exercitation minim. Lorem sit reprehenderit cupidatat tempor aute. Consectetur Lorem id reprehenderit esse laboris qui proident exercitation amet labore sit pariatur sint incididunt. Ullamco laborum enim elit excepteur adipisicing mollit nisi irure veniam laborum minim duis. Enim fugiat magna cupidatat occaecat tempor dolore nostrud Lorem eu nostrud officia ad anim adipisicing.\r\n',
  },
  {
    id: 73,
    username: 'DotsonJoseph',
    firstName: 'Kimberly',
    lastName: 'Short',
    email: 'kimberlyshort@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 947629888,
    status: 'Contract',
    group: 'IT Support',
    description:
      'Aute anim anim laboris consequat excepteur. Anim ea magna Lorem cupidatat laborum irure pariatur amet occaecat enim. Dolor incididunt laboris pariatur id ullamco quis non consectetur quis adipisicing deserunt. Tempor dolor occaecat eiusmod magna consectetur quis cupidatat labore. Veniam fugiat Lorem mollit veniam magna ut laboris. Cillum voluptate fugiat esse deserunt.\r\n',
  },
  {
    id: 74,
    username: 'BrigitteKinney',
    firstName: 'Claudine',
    lastName: 'Webb',
    email: 'claudinewebb@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 931911211,
    status: 'Permanent',
    group: 'Mobile',
    description:
      'Nostrud excepteur ex velit duis nulla esse officia culpa deserunt Lorem. Enim magna ipsum magna do Lorem officia excepteur cupidatat. Magna dolore quis culpa Lorem eiusmod fugiat culpa consectetur officia. Mollit irure incididunt occaecat exercitation. Laboris nulla adipisicing commodo proident ipsum enim amet magna do laboris elit.\r\n',
  },
  {
    id: 75,
    username: 'BarnettYang',
    firstName: 'Darla',
    lastName: 'Arnold',
    email: 'darlaarnold@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 816686837,
    status: 'Contract',
    group: 'Digital developer',
    description:
      'Non enim nostrud laboris nisi eiusmod amet magna sit veniam ad. Irure deserunt qui exercitation culpa nostrud nisi non. Elit minim sit non id id ullamco ullamco mollit adipisicing duis irure reprehenderit cupidatat. Aliqua minim tempor cupidatat id.\r\n',
  },
  {
    id: 76,
    username: 'BlankenshipBoone',
    firstName: 'Silva',
    lastName: 'Jarvis',
    email: 'silvajarvis@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 902851631,
    status: 'Contract',
    group: 'Mobile',
    description:
      'Amet qui dolore ea pariatur fugiat veniam eiusmod. Magna fugiat labore elit nostrud quis velit enim Lorem elit. Reprehenderit sunt esse velit id. Eiusmod duis nostrud et ullamco dolor excepteur tempor incididunt adipisicing.\r\n',
  },
  {
    id: 77,
    username: 'GraceMcclure',
    firstName: 'Norton',
    lastName: 'Small',
    email: 'nortonsmall@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 815185817,
    status: 'Contract',
    group: 'Frontend',
    description:
      'Irure proident esse cupidatat et quis nostrud reprehenderit in do Lorem ex ad. Mollit cupidatat adipisicing dolore non labore elit est nisi et cillum laboris culpa. Cupidatat mollit exercitation adipisicing pariatur ea anim in mollit est aliqua dolore ullamco commodo. Ut amet cillum id nostrud aliquip adipisicing nulla ut ullamco consectetur eu mollit. Do tempor ad adipisicing elit enim duis consequat laboris non laboris ad excepteur. Proident exercitation aute esse reprehenderit mollit consectetur excepteur in culpa et mollit adipisicing aliqua.\r\n',
  },
  {
    id: 78,
    username: 'VickieRandolph',
    firstName: 'Hodge',
    lastName: 'Strong',
    email: 'hodgestrong@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 820423851,
    status: 'Permanent',
    group: 'Digital developer',
    description:
      'Officia qui velit ut cillum cillum non qui nostrud exercitation ipsum. Irure consectetur ut cupidatat ut. Magna eu cupidatat est cupidatat commodo exercitation sint minim duis ipsum ea qui. Fugiat adipisicing fugiat velit ut ut do nostrud ea elit in minim tempor. Ipsum commodo ex enim Lorem esse labore laboris veniam in adipisicing irure est commodo. Minim aliqua cillum consectetur cupidatat Lorem consequat. Qui eiusmod veniam nostrud sint.\r\n',
  },
  {
    id: 79,
    username: 'BoyleDonaldson',
    firstName: 'Bryan',
    lastName: 'Alexander',
    email: 'bryanalexander@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 951337016,
    status: 'Permanent',
    group: 'IT Support',
    description:
      'Velit proident ea in ipsum et adipisicing laboris. Et adipisicing reprehenderit in deserunt ex dolor aliquip minim Lorem consequat est quis magna. Tempor dolor mollit minim est enim veniam tempor velit culpa veniam. Commodo ut ut velit cillum ad qui dolore. Labore minim proident sunt culpa adipisicing ad non enim eiusmod. Dolore enim irure Lorem id id qui eu excepteur elit qui irure. Id velit elit qui nisi ullamco consequat.\r\n',
  },
  {
    id: 80,
    username: 'StephanieCalderon',
    firstName: 'Wade',
    lastName: 'Ayala',
    email: 'wadeayala@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 919475223,
    status: 'Contract',
    group: 'System Analyst',
    description:
      'Ullamco sunt elit cupidatat do est sit et culpa nostrud et. Magna occaecat incididunt do enim occaecat deserunt ex nostrud voluptate. Culpa ullamco occaecat amet pariatur reprehenderit nisi consequat occaecat nostrud eu dolore. Labore ea mollit dolor tempor duis sit nostrud do fugiat veniam deserunt et ex. Reprehenderit tempor ullamco anim laborum ea elit. Culpa Lorem mollit incididunt commodo eiusmod pariatur fugiat ullamco amet.\r\n',
  },
  {
    id: 81,
    username: 'WallsYates',
    firstName: 'David',
    lastName: 'Vang',
    email: 'davidvang@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 968345544,
    status: 'Permanent',
    group: 'Digital Banking',
    description:
      'Id sint laborum cupidatat ipsum sint do nulla proident quis et ipsum irure. Laborum anim ex eiusmod dolore. Eu Lorem consequat et excepteur anim ea incididunt proident esse quis enim consequat commodo non. Proident do elit adipisicing esse sunt mollit tempor pariatur consectetur. Et amet ipsum mollit reprehenderit. Lorem anim ea aliqua enim laborum et esse amet enim commodo mollit anim veniam. Labore officia commodo qui elit et id duis sunt.\r\n',
  },
  {
    id: 82,
    username: 'KirbyDuran',
    firstName: 'Cristina',
    lastName: 'Lester',
    email: 'cristinalester@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 846572485,
    status: 'Permanent',
    group: 'System Analyst',
    description:
      'Ad aute nulla quis irure consectetur cillum sint cupidatat mollit veniam proident veniam qui eiusmod. Cupidatat sint deserunt mollit labore. Adipisicing tempor dolore proident nisi fugiat ullamco duis in culpa fugiat anim incididunt aute occaecat.\r\n',
  },
  {
    id: 83,
    username: 'BrigitteKinney',
    firstName: 'Claudine',
    lastName: 'Webb',
    email: 'claudinewebb@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 931911211,
    status: 'Permanent',
    group: 'Mobile',
    description:
      'Nostrud excepteur ex velit duis nulla esse officia culpa deserunt Lorem. Enim magna ipsum magna do Lorem officia excepteur cupidatat. Magna dolore quis culpa Lorem eiusmod fugiat culpa consectetur officia. Mollit irure incididunt occaecat exercitation. Laboris nulla adipisicing commodo proident ipsum enim amet magna do laboris elit.\r\n',
  },
  {
    id: 84,
    username: 'BarnettYang',
    firstName: 'Darla',
    lastName: 'Arnold',
    email: 'darlaarnold@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 816686837,
    status: 'Contract',
    group: 'Digital developer',
    description:
      'Non enim nostrud laboris nisi eiusmod amet magna sit veniam ad. Irure deserunt qui exercitation culpa nostrud nisi non. Elit minim sit non id id ullamco ullamco mollit adipisicing duis irure reprehenderit cupidatat. Aliqua minim tempor cupidatat id.\r\n',
  },
  {
    id: 85,
    username: 'BlankenshipBoone',
    firstName: 'Silva',
    lastName: 'Jarvis',
    email: 'silvajarvis@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 902851631,
    status: 'Contract',
    group: 'Mobile',
    description:
      'Amet qui dolore ea pariatur fugiat veniam eiusmod. Magna fugiat labore elit nostrud quis velit enim Lorem elit. Reprehenderit sunt esse velit id. Eiusmod duis nostrud et ullamco dolor excepteur tempor incididunt adipisicing.\r\n',
  },
  {
    id: 86,
    username: 'GraceMcclure',
    firstName: 'Norton',
    lastName: 'Small',
    email: 'nortonsmall@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 815185817,
    status: 'Contract',
    group: 'Frontend',
    description:
      'Irure proident esse cupidatat et quis nostrud reprehenderit in do Lorem ex ad. Mollit cupidatat adipisicing dolore non labore elit est nisi et cillum laboris culpa. Cupidatat mollit exercitation adipisicing pariatur ea anim in mollit est aliqua dolore ullamco commodo. Ut amet cillum id nostrud aliquip adipisicing nulla ut ullamco consectetur eu mollit. Do tempor ad adipisicing elit enim duis consequat laboris non laboris ad excepteur. Proident exercitation aute esse reprehenderit mollit consectetur excepteur in culpa et mollit adipisicing aliqua.\r\n',
  },
  {
    id: 87,
    username: 'VickieRandolph',
    firstName: 'Hodge',
    lastName: 'Strong',
    email: 'hodgestrong@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 820423851,
    status: 'Permanent',
    group: 'Digital developer',
    description:
      'Officia qui velit ut cillum cillum non qui nostrud exercitation ipsum. Irure consectetur ut cupidatat ut. Magna eu cupidatat est cupidatat commodo exercitation sint minim duis ipsum ea qui. Fugiat adipisicing fugiat velit ut ut do nostrud ea elit in minim tempor. Ipsum commodo ex enim Lorem esse labore laboris veniam in adipisicing irure est commodo. Minim aliqua cillum consectetur cupidatat Lorem consequat. Qui eiusmod veniam nostrud sint.\r\n',
  },
  {
    id: 88,
    username: 'BoyleDonaldson',
    firstName: 'Bryan',
    lastName: 'Alexander',
    email: 'bryanalexander@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 951337016,
    status: 'Permanent',
    group: 'IT Support',
    description:
      'Velit proident ea in ipsum et adipisicing laboris. Et adipisicing reprehenderit in deserunt ex dolor aliquip minim Lorem consequat est quis magna. Tempor dolor mollit minim est enim veniam tempor velit culpa veniam. Commodo ut ut velit cillum ad qui dolore. Labore minim proident sunt culpa adipisicing ad non enim eiusmod. Dolore enim irure Lorem id id qui eu excepteur elit qui irure. Id velit elit qui nisi ullamco consequat.\r\n',
  },
  {
    id: 89,
    username: 'StephanieCalderon',
    firstName: 'Wade',
    lastName: 'Ayala',
    email: 'wadeayala@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 919475223,
    status: 'Contract',
    group: 'System Analyst',
    description:
      'Ullamco sunt elit cupidatat do est sit et culpa nostrud et. Magna occaecat incididunt do enim occaecat deserunt ex nostrud voluptate. Culpa ullamco occaecat amet pariatur reprehenderit nisi consequat occaecat nostrud eu dolore. Labore ea mollit dolor tempor duis sit nostrud do fugiat veniam deserunt et ex. Reprehenderit tempor ullamco anim laborum ea elit. Culpa Lorem mollit incididunt commodo eiusmod pariatur fugiat ullamco amet.\r\n',
  },
  {
    id: 90,
    username: 'WallsYates',
    firstName: 'David',
    lastName: 'Vang',
    email: 'davidvang@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 968345544,
    status: 'Permanent',
    group: 'Digital Banking',
    description:
      'Id sint laborum cupidatat ipsum sint do nulla proident quis et ipsum irure. Laborum anim ex eiusmod dolore. Eu Lorem consequat et excepteur anim ea incididunt proident esse quis enim consequat commodo non. Proident do elit adipisicing esse sunt mollit tempor pariatur consectetur. Et amet ipsum mollit reprehenderit. Lorem anim ea aliqua enim laborum et esse amet enim commodo mollit anim veniam. Labore officia commodo qui elit et id duis sunt.\r\n',
  },
  {
    id: 90,
    username: 'SandovalGolden',
    firstName: 'Ebony',
    lastName: 'Dale',
    email: 'ebonydale@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 897117892,
    status: 'Contract',
    group: 'Frontend',
    description:
      'Minim exercitation nulla qui nisi. Ullamco esse qui laborum sint cupidatat exercitation incididunt consectetur enim et laboris eu. Ipsum minim eu exercitation ex. Et eiusmod anim ut dolor sit sit magna velit do fugiat elit nostrud laboris.\r\n',
  },
  {
    id: 91,
    username: 'BobbieMccoy',
    firstName: 'Whitfield',
    lastName: 'Juarez',
    email: 'whitfieldjuarez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 923297430,
    status: 'Contract',
    group: 'Digital Banking',
    description:
      'Quis eu dolor proident esse fugiat Lorem minim irure anim sint pariatur nostrud. Minim esse ea eu occaecat culpa. Aliqua adipisicing nulla laboris ea adipisicing incididunt ullamco ex. Adipisicing mollit deserunt deserunt laborum pariatur amet culpa fugiat sint consectetur adipisicing incididunt reprehenderit deserunt. Ullamco do eiusmod voluptate sint magna laborum. Nulla magna adipisicing nulla dolore cupidatat consectetur.\r\n',
  },
  {
    id: 92,
    username: 'StantonKnox',
    firstName: 'Petty',
    lastName: 'Lawrence',
    email: 'pettylawrence@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 943383779,
    status: 'Contract',
    group: 'Digital Banking',
    description:
      'Tempor in anim aliquip pariatur culpa dolore excepteur nisi cillum nostrud dolore nisi proident. Occaecat est aliquip adipisicing velit voluptate aliquip reprehenderit ullamco aliquip pariatur pariatur. Quis eu velit enim excepteur duis eiusmod tempor qui. Magna cillum et minim ipsum aliqua sunt commodo nulla mollit deserunt. Eiusmod culpa magna deserunt velit ad voluptate velit nostrud. Anim fugiat qui nulla reprehenderit tempor in qui consectetur labore tempor. Voluptate eu labore occaecat Lorem mollit.\r\n',
  },
  {
    id: 93,
    username: 'JeanetteSchmidt',
    firstName: 'Trudy',
    lastName: 'Duffy',
    email: 'trudyduffy@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 843203813,
    status: 'Contract',
    group: 'Database',
    description:
      'Mollit sit ipsum cillum dolore proident sit velit aute consectetur. Mollit tempor labore id Lorem ullamco consectetur veniam ipsum amet duis amet incididunt esse. Est aliqua do adipisicing fugiat ea anim tempor incididunt eu pariatur.\r\n',
  },
  {
    id: 94,
    username: 'WarrenMoon',
    firstName: 'Fry',
    lastName: 'Holmes',
    email: 'fryholmes@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 948126984,
    status: 'Contract',
    group: 'Backend',
    description:
      'In in irure ea ut commodo commodo. Dolor consectetur id anim deserunt anim. Nisi fugiat fugiat commodo cillum magna deserunt. Lorem commodo ex anim deserunt sunt.\r\n',
  },
  {
    id: 95,
    username: 'KnightFlowers',
    firstName: 'Lancaster',
    lastName: 'Cooper',
    email: 'lancastercooper@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 941664047,
    status: 'Permanent',
    group: 'Frontend',
    description:
      'Veniam laboris ex adipisicing quis anim ut velit sunt sint est ea. Enim ad proident esse incididunt est voluptate tempor velit labore do aliqua. Ex voluptate Lorem nostrud enim consequat quis aliqua commodo ullamco reprehenderit officia.\r\n',
  },
  {
    id: 96,
    username: 'DouglasBowman',
    firstName: 'Selena',
    lastName: 'Mcintyre',
    email: 'selenamcintyre@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 880224396,
    status: 'Permanent',
    group: 'UI/UX',
    description:
      'Nulla incididunt ullamco ex sint minim. Ex aliqua elit eiusmod minim incididunt qui eiusmod qui sunt veniam duis commodo ipsum. Cillum labore esse dolore ullamco commodo consectetur irure aliquip deserunt quis labore laboris consequat. Consectetur fugiat proident sunt occaecat excepteur cupidatat sunt Lorem dolore cupidatat enim id et. Sit aute proident consequat nisi deserunt ut dolore aute qui nisi magna ut voluptate. Proident non ut eiusmod amet adipisicing ullamco consectetur laboris ullamco consequat. Veniam enim ut et non consectetur laborum voluptate aliqua.\r\n',
  },
  {
    id: 97,
    username: 'MooneyMckay',
    firstName: 'Camille',
    lastName: 'Moreno',
    email: 'camillemoreno@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 884444261,
    status: 'Contract',
    group: 'Frontend',
    description:
      'Nisi laborum voluptate culpa aliqua do reprehenderit in consequat. Quis qui consequat laborum veniam aliquip nostrud esse aliqua consectetur esse ad. Dolor ut non laborum consequat nisi dolore enim culpa in. Ullamco proident aliqua nisi ullamco. Cupidatat id excepteur ipsum laboris dolor nisi officia voluptate occaecat voluptate officia. Nostrud ut mollit est ea velit deserunt veniam officia reprehenderit ad. Minim exercitation adipisicing veniam officia eiusmod.\r\n',
  },
  {
    id: 98,
    username: 'FrancisBurton',
    firstName: 'Jane',
    lastName: 'Rodriquez',
    email: 'janerodriquez@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 815385667,
    status: 'Permanent',
    group: 'Frontend',
    description:
      'Exercitation dolore velit reprehenderit elit magna laboris reprehenderit. Lorem commodo ea eu tempor labore quis minim. Enim mollit sit amet fugiat dolor qui. Eu dolor eu nostrud adipisicing sit duis. Culpa reprehenderit voluptate eiusmod exercitation et mollit consequat sit non sit exercitation eiusmod amet.\r\n',
  },
  {
    id: 99,
    username: 'CantrellRiley',
    firstName: 'Darcy',
    lastName: 'Hampton',
    email: 'darcyhampton@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 818309335,
    status: 'Permanent',
    group: 'Security',
    description:
      'Fugiat deserunt reprehenderit laboris cillum ea. Duis ea irure mollit non nulla mollit dolor anim officia. Anim reprehenderit fugiat id tempor ex fugiat incididunt enim adipisicing mollit incididunt do.\r\n',
  },
  {
    id: 100,
    username: 'TranRios',
    firstName: 'Felicia',
    lastName: 'Ray',
    email: 'feliciaray@quilk.com',
    birthDate: new Date('1991-08-05'),
    basicSalary: 841900417,
    status: 'Permanent',
    group: 'Digital developer',
    description:
      'Incididunt anim officia excepteur incididunt anim. Nostrud dolor culpa elit ipsum exercitation aliquip. Adipisicing fugiat ipsum eu qui excepteur sit enim veniam id labore nisi proident quis. Qui cupidatat adipisicing amet tempor est deserunt incididunt tempor proident cillum duis do excepteur eiusmod.\r\n',
  },
];

export const search: Search[] = [
  {
    name: 'digital',
  },
];
